microsoft/MSBuildCache

src/SharedCompilation/Microsoft.MSBuildCache.SharedCompilation.csproj
version.json

This should fix the version we push to nuget.org from something like `0.1.223-preview-g7f2aa10a8b` to something like `0.1.223-preview`.
Also fix signing for the SharedCompilation package

Consider tagged refs as public releases

---

src/Common/MSBuildCachePluginBase.cs

I noticed that copies of nuget package contents only showed the destination of the copy and not the source. The reason was that we are filtering out any file access outside the repo. This was a bad early decision probably originally to help scope down the file access logs.
We will almost certainly want to start considering file accesses outside the repo, for example the package cache. Actual handling of those inputs will come in a future change though.

Stop filtering file accesses not under the repo root

---

tests/TestProject/.gitignore
tests/test.ps1

Previously the fingerprints would be mostly empty due to the temp location it was running in not being included in the parent git repo. This creates a new git repo in the directory where the test source is copied to.

Create dummy git repo for e2e test for proper hashing

---

src/Common/Parsing/ProjectPredictionCollector.cs

If the predicted input directory does not exist yet, eg if it's an output directory, then the `Directory.EnumerateFiles` fails.
Furthermore, the path is normalized (enlistment-relative) and that path is enumerated, but the cwd may not be the repo root, so this is just plain incorrect.
This change fixes these by checking for directory existence and using the absolute path for the enumerate call.

Fix prediction of generated input directories

---

src/SharedCompilation/VBCSCompilerReporter.cs
tests/TestProject/Directory.Build.props

This uses some fancy dynamic method shenanigans to adjust to https://github.com/dotnet/msbuild/pull/9615. This should be able to handle the MSBuild version we compile against as well as the new version.

Adjust to breaking change in FileAccessData ctor

---

src/Common/FileAccess/FileAccessRepository.cs
src/Common/PathHelper.cs

Previously we were converting to a span, doing some operations, then converting back to a string. Usually the operation is a no-op though as most paths are not long paths, so this was allocating for no reason.
Beyond switching to just using a simple string, the optimized path short-circuits in the common case of not being a long path so is also much faster than the original logic anyway. In fact, at least for net8.0, BenchmarkDotNet says for the common case: "The method duration is indistinguishable from the empty method duration". So that's cool.

Optimize RemoveLongPathPrefixes

---

src/AzurePipelines/PipelineCachingCacheClient.cs

We've seen some networking glitches and so we'll reduce timeouts from the default of 100 seconds and we'll also lower parallelism.  We'll make both configurable for more testing.

Tighten timeouts and lower parallelism

---

src/Common/FileAccess/FileAccessRepository.cs

Use a shared process table to help aid AllowFileAccessAfterProjectFinishProcessPatterns
Recently I saw this error:
> System.InvalidOperationException: File access reported from process `ProcessId: 15812` after the project finished. This may lead to incorrect caching. Node Id: SRC_MODULES_PREVIEWPANE_UNITTESTS-PREVIEWHANDLERCOMMON_UNITTESTS-PREVIEWHANDLERCOMMON.CSPROJ_Q1.MFK9ZW6VAZNSVCNNXLA, Path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrcompression.dll
Process 15812 in this case is vctip.exe and `AllowFileAccessAfterProjectFinishProcessPatterns` is set to `\**\vctip.exe`, however based on the fact that it was referred to as "ProcessId: 15812" instead of the path to vctip.exe means that `AllowFileAccessAfterProjectFinishProcessPatterns` wasn't properly checked.
Upon …

Use a shared process table to help aid AllowFileAccessAfterProjectFinishProcessPatterns

---

src/Common/FileAccess/FileAccessRepository.cs

Remove longpath prefixes before using AllowFileAccessAfterProjectFinishFilePatterns
Recently saw this error:
```
Unhandled Exception: System.InvalidOperationException: File access reported from process `ProcessId: 7636` after the project finished. This may lead to incorrect caching. Node Id: SRC_MODULES_MOUSEWITHOUTBORDERS_MODULEINTERFACE_MOUSEWITHOUTBORDERSMODULEINTERFACE.VCXPROJ_FHZ6ITP5WQGQQON5O.UXJW, Path: \\?\C:\Users\cloudtest\AppData\Local\Microsoft\VSApplicationInsights\vstelAIF-312cbd79-9dbb-4c48-a7da-3cc2a931cb70
```
Despite having `MSBuildCacheAllowFileAccessAfterProjectFinishFilePatterns` contain `$(LocalAppData)\Microsoft\VSApplicationInsights\**`. This appears to be due to the `\\?\` prefix.
This change removes the longpath prefixes earlier so we never are evaluating paths …

Remove longpath prefixes before using AllowFileAccessAfterProjectFinishFilePatterns

---

src/AzurePipelines/PipelineCachingCacheClient.cs
src/Common/PathHelper.cs

Remove more usage of AbsolutePath to avoid long path prefix issues

Remove more usage of AbsolutePath to avoid long path prefix issues

---

src/Common/FileAccess/FileAccessRepository.cs

Fix race condition in FileAccessRepository
Today when we allow file accesses after project completion, we avoid disposing the log file stream and relevant to this bug we also avoid nulling out the `fileTable` and `deletedDirectories`. *outside* the lock we enumerate these collections to return a `FileAccesses` to the plugin. If a file access comes in while we're enumerating, we can get an exception like this:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at …
```

Fix race condition in FileAccessRepository

---

src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs
src/AzurePipelines/MSBuildCacheAzurePipelinesPlugin.cs
src/AzurePipelines/PipelineCachingCacheClient.cs
src/Common.Tests/NodeBuildResultTests.cs
src/Common/Caching/CacheClient.cs
src/Common/Caching/CasCacheClient.cs
src/Common/Fingerprinting/FingerprintFactory.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/NodeBuildResult.cs
src/Local/MSBuildCacheLocalPlugin.cs
tests/TestProject/TestProject.csproj
tests/test.ps1

A non-trivial part of builds is simply copying content from packages and there's no need to duplicate that content into the build cache when the package cache should already contain the files. As packages are expected to be immutable, this should be a safe operation.
In my test repo with 100% cache hits, this saves ~50% of the build time (pulling everything from blob storage cache) and cuts the remote storage by about ~50% as well. Note that this test was on residential internet, so that 50% build time savings may not be completely representative if the CI build agents have a super fast connection to the storage, but the storage cost savings should be.
This change does a couple things:
* When processing a node in `HandleProjectFinished` ("cache add")
* While enumerating the inputs, keep …

Copy package files from the package cache instead of ingesting them into the build cache

---

src/Common/Fingerprinting/FingerprintFactory.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/NodeContext.cs
src/Common/NodeDescriptor.cs
src/Common/NodeDescriptorFactory.cs

The current behavior uses the full set of global properties to generate the ids, which may be different from build to build since it may contain `MSBuildCacheLogDirectory` for example. We filter some global properties when fingerprinting, so we should use those same filtered global properties for the ids.
This usually doesn't really matter, but there are two case which it does. The first is that it just makes diffing across builds more difficult when they don't line up. More importantly though, this can cause cache misses for outer builds where the (dependent) inner builds end up sorting differently based on the id differences. eg if a multitargeting project targeting net8.0 and net472, the fingerprint for the outer build would contain both inner builds as dependencies and those obviously …

Use filtered global properties for node ids

---

.azuredevops/pipelines/pr-ci.yml
.azuredevops/pipelines/templates/variables.yml
CONTRIBUTING.md
Directory.Packages.props
src/Common/MSBuildCachePluginBase.cs
src/Repack.Tests/RepackTests.cs
src/SharedCompilation/VBCSCompilerReporter.cs

This consumes the requested targets so that scenarios using the non-default targets (eg `msbuild /t:Build;Test`) can be properly supported.
Related MSBuild PR: https://github.com/dotnet/msbuild/pull/9569
Note that this sets a new minimum supported MSBuild versions as 17.9, which also allowed cleanup of some compat-related code.

Consume requested targets when constructing the graph

---

src/Common/Caching/CacheClient.cs

We're seeing these copies collide with each other and fail due to sharing violation. Avoid them in the first place.

merge duplicate placements from packages

---

.azuredevops/pipelines/official.yml
.azuredevops/pipelines/pr-ci.yml
.azuredevops/pipelines/templates/network-isolation.yml
.azuredevops/pipelines/templates/variables.yml

The task will default to be disabled for the time being and avoid breaking the build if something goes wrong but can be enabled in Audit or Enforce mode on manual pipeline runs.

Add disabled NI task on pipeline builds

---

src/Common/Fingerprinting/FingerprintFactory.cs

Add VCToolsVersion and NETCoreSdkVersion properties to fingerprints
These are to help with the situation of build tooling like VS updating and some projects coming from cache from the old version while newer projects are rebuilt.
For `VCToolsVersion`, the linker is not able to handle obj files which were compiled with different versions of the compiler:
> LINK(0,0): Error C1047: The object or library file 'D:\a\_work\1\s\x64\Release\spdlog.lib' was created by a different version of the compiler than other objects like 'x64\Release\dllmain.obj'; rebuild all objects and libraries with the same compiler
For `NETCoreSdkVersion`, upgrading the SDK may upgrade the bundled runtime runtime. This can lead to an older runtime being copied, which fails as it's usually no longer installed, not to …

Add VCToolsVersion and NETCoreSdkVersion properties to fingerprints

---

README.md
src/AzureBlobStorage/AzureBlobStoragePluginSettings.cs
src/AzureBlobStorage/AzureStorageCredentialsType.cs
src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs
src/AzureBlobStorage/build/Microsoft.MSBuildCache.AzureBlobStorage.targets
src/Common/PluginSettings.cs
src/Common/SourceControl/GitFileHashProvider.cs

This change adds additional credential types to the AzureBlobStorage plugin, including interactive auth and using a managed identity.

AzureBlobStorage: Add interactive and MI auth

---

src/Common/Fingerprinting/FingerprintFactory.cs
src/Common/MSBuildCachePluginBase.cs

Tolerate dependencies outside the repo when adding to cache.
This supports scenarios like NerdBank.GitVersioning which end up adding a projects inside the package to the graph, which ends up getting ignored.
> Ignoring project outside the repository: D:\Code\.nuget\nerdbank.gitversioning\3.6.139\build\PrivateP2PCaching.proj
Before this change, this would result in all cache misses for repos using NerdBank.GitVersioning.
Note that projects outside of the repo which are built in this manner are not considered at all for cache fingerprinting, so any changes in those projects will not cause projects to rebuild, just like any other file read outside the repo (and outside NuGet packages).

Tolerate dependencies outside the repo when adding to cache

---

src/Common/Caching/CacheClient.cs

Fixes #85
I'm following up with the BXL team about this, but this should mitigate in the meantime.

Mitigate bug in BXL's log disposal

---

src/Common/SourceControl/Git.cs

Avoid setting Console.InputEncoding

---

src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs

Blob: Create InteractiveAuthTokenDirectory if needed
`InteractiveClientStorageCredentials` will throw an exception and then swallow it if `InteractiveAuthTokenDirectory` does not already exist, causing an auth popup to happen every time.
This creates the directory proactively to avoid this.
I'm also following up with the BuildXL team to get a fix into `InteractiveClientStorageCredentials`.

Blob: Create InteractiveAuthTokenDirectory if needed

---

README.md
src/Common.Tests/PluginSettingsTests.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/PluginSettings.cs
src/Common/build/Microsoft.MSBuildCache.Common.targets

Add ability to query nodes recursively if needed
This feature allows the plugin to on-demand query for dependencies which have not been queried. Most scenarios are expected to do a "graph build" and ensure all dependencies are built first, but some upcoming scenarios might violate that constraint.
This is an opt-in scenario since it adds some overhead and can make cache misses more expensive.

Add ability to query nodes recursively if needed

---

src/Common/Fingerprinting/FingerprintFactory.cs

This can help with cache hits when the cache producer and cache consumer aren't _exactly_ the same VS version. C++ projects must have the same compiler version, but we can be a bit looser with other project types.

Only add VCToolsVersion to the fingerprint for vcxproj projects

---

src/Common/SourceControl/Git.cs
src/Common/SourceControl/GitProcess.cs

Well, I thought wrapping the underlying stream with a writer with another encoder would work (see #84), but it appears that `Process` sets `AutoFlush`, which immediately writes that encoding's preamble (the BOM in this case) to the stream.
After a bunch of trial and error, I couldn't figure out a way to start a process using `Process` without writing a BOM to stdin, so decided to just completely copy/paste the `Process` class and customize it, which really is a terrible workaround. I did remove a bunch of the unused features though to save a few thousand lines of copy/pasted code from .NET Framework, but it's still a pretty huge amount of copy/paste.
Oh well, I guess it works.

Fix stdin encoding for Git... again

---

README.md
src/AzureBlobStorage/AzureStorageCredentialsType.cs
src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs

Env vars prefixed by "MSBuild" automatically get logged, and since this one contains a secret, that's a bad thing.
This renames the environment variable to avoid this.
Note that this is a breaking change!

Change MSBUILDCACHE_CONNECTIONSTRING -> MSBCACHE_CONNECTIONSTRING

---

README.md
src/AzureBlobStorage/AzureStorageCredentialsType.cs
src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs
src/AzureBlobStorage/StaticTokenCredential.cs
src/AzureBlobStorage/TokenCredentialAzureStorageCredentials.cs

This adds a new authentication type which can be used either by providing an access token via env var, or by providing a `TokenCredential` (or access token) in the ctor (when using the programmatic project cache API)

Blob: Add TokenCredential auth

---

Directory.Packages.props
global.json
src/Common.Tests/Microsoft.MSBuildCache.Common.Tests.csproj
src/Repack.Tests/Microsoft.MSBuildCache.Repack.Tests.csproj

Reverts microsoft/MSBuildCache#99
Broken official builds. Something about strong naming. Ugh.
```
D:\a\_work\1\s\src\Repack.Tests\bin\x64\Release\net472\Microsoft.MSBuildCache.Repack.Tests.exe : error run failed: Tests failed:  [D:\a\_work\1\s\src\Repack.Tests\Microsoft.MSBuildCache.Repack.Tests.csproj::TargetFramework=net472]
D:\a\_work\1\s\src\Repack.Tests\bin\x64\Release\net472\Microsoft.MSBuildCache.Repack.Tests.exe : error run failed: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.MSBuildCache.Repack.Tests, Version=0.1.0.0, Culture=neutral, PublicKey***=6702f781b82f5f3b' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. …
```

Revert "Migrate test projects to MSTest.Sdk"

---

README.md
src/Common.Tests/PluginSettingsTests.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/PluginSettings.cs
src/Common/build/Microsoft.MSBuildCache.Common.props
src/Common/build/Microsoft.MSBuildCache.Common.targets

Add ability to ignore targets when determining if a build request matches a cache entry

Add ability to ignore targets when determining if a build request matches a cache entry

---

src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs
src/Common/SourceControl/Git.cs

The original intent was to match Azure Pipeline Caching which has a hierarchy of caches, where the current branch has a Read/Write cache, while parent branches like `main` would have a cache with read-only access. [Details](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#cache-isolation-and-security) for the interested for how that works.
However, this simply added the branch name to the cache universe, which isolated but did not actually add any security. It also didn't add any of the hierarchy logic, meaning branches were _completely_ isolated, which is not desirable.
This change just removes that logic.

Blob: Remove branch from cache universe

---

Directory.Packages.props
build/MSBuildExtensionPackage.targets
src/AzureBlobStorage/MSBuildCacheAzureBlobStoragePlugin.cs

Update BuildXL packages
This matches the package version MSBuild is now using, as well as contains a couple useful fixes for us, specifically for the blob implementation:
* `InteractiveAuthTokenDirectory` is now created if it doesn't exist
* Interactive auth now supports WAM

Update BuildXL packages

---

src/Common/Caching/CacheClient.cs

This moves the call to after the await for the placement tasks. Previously those tasks might still be executing so could lead to a race condition where the output file didn't exist on disk yet.
Example exception that was being seen previously:
```
System.IO.FileNotFoundException: Could not find file '<redacted>'.
File name: '<redacted>'
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileInfo.get_Length()
at Microsoft.MSBuildCache.Caching.LocalCacheStateManager.<WriteStateFileAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Common\Caching\LocalCacheStateManager.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at …
```

Fix race condition for writing local cache state

---

src/Common/Caching/CacheClient.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/PluginSettings.cs
src/Common/SourceControl/Git.cs

This avoid logging a warning when cancellation is requested and instead logs a debug level message.
There is also some light refactoring of the sync TimeAndLog path to avoid Task overhead.
Note that cancellation exceptions are still rethrown now which crashes MSBuild. This will need to be addressed from within MSBuild itself.

Avoid logging warnings when cancellation is requested

---

src/Common/Caching/LocalCacheStateManager.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/NodeContext.cs
src/Common/Parsing/Parser.cs
src/Common/Parsing/ProjectPredictionCollector.cs

This change touches up-to-date files when the `MSBuildCacheSkipUnchangedOutputFiles` feature is being used. This helps incremental builds understand that the files are up-to-date as well.
There is a special case for ref assemblies, as there is a strong dependency on that file *not* being updated when it does not change.

Touch up-to-date files to assist incremental builds

---

src/Common/Caching/CacheClient.cs
src/Common/Caching/ICacheClient.cs
src/Common/MSBuildCachePluginBase.cs
src/Common/ProjectInstanceExtensions.cs

When using the `MSBuildCacheGetResultsForUnqueriedDependencies` feature, today the unqueried dependencies' outputs are materialized on disk, assuming they're cache hits. This is problematic because the caller did not explicitly ask for those nodes and thus may be assuming that those outputs are not changing in any way.
This change avoids materializing outputs for unqueried dependencies.
There is special-casing for outer builds of multitargeting projects. Outer builds depend on the inner builds, so if only the outer build were materialized, almost nothing would end up materializing. So we do still materialize dependencies if the project is an outer build and the dependency is an inner build.
Note that there was some debate around this (I was the hold-out), so capturing the gist of the …

Avoid materializing outputs for unqueried dependencies

---

src/Common/build/Microsoft.MSBuildCache.Common.props

Disable NuGet fallback dir to avoid non-determinism.
This can cause differing fingerprints leading to cache misses:
This change disables the defunct feature (it no longer ships with recent versions of the SDK).

Disable NuGet fallback dir to avoid non-determinism

---

Directory.Packages.props

The primary motivation is to get https://github.com/microsoft/CopyOnWrite/pull/52, which removes some overhead of `async` calls (which were always synchronous anyway).
Since in Windows 11 24H2, CoW is automatic, we should consider at some point removing this and letting the OS handle it.

Update CopyOnWrite to 0.5.0
